# Generated by Django 5.1.2 on 2025-03-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("size", models.CharField(max_length=100)),
                ("climate", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zookeeper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("qualification", models.CharField(max_length=100)),
                ("responsibilities", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("diet", models.CharField(max_length=100)),
                ("lifespan", models.PositiveIntegerField()),
                ("behaviour", models.CharField(max_length=500)),
                ("habitat", models.ManyToManyField(to="system.habitat")),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="system.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeding_time", models.TimeField()),
                ("diet", models.CharField(max_length=100)),
                ("medical_needs", models.TextField(blank=True)),
                (
                    "zookeepers",
                    models.ManyToManyField(
                        related_name="care_routines", to="system.zookeeper"
                    ),
                ),
            ],
        ),
    ]
