# Generated by Django 5.1.2 on 2025-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="behavior",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="diet",
            field=models.CharField(
                choices=[
                    ("Herbivore", "Herbivore"),
                    ("Carnivore", "Carnivore"),
                    ("Omnivore", "Omnivore"),
                ],
                default="Herbivore",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="lifespan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitat",
            name="climate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="habitat",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="habitat",
            name="suitable_species",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitat",
            name="name",
            field=models.CharField(
                default="Savanna Plains", max_length=50, unique=True
            ),
        ),
    ]
